// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA_M10xOxk5-4N96EPkd2PDvPQNlnXS68',
    appId: '1:878308519120:web:efeff2042aa80e7d9682d5',
    messagingSenderId: '878308519120',
    projectId: 'waged-medical',
    authDomain: 'waged-medical.firebaseapp.com',
    storageBucket: 'waged-medical.appspot.com',
    measurementId: 'G-K9B3LHWJMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIUv2jw6f3vq2vFulvO3mPqHWLHbkZAg0',
    appId: '1:878308519120:android:681fa23c705a94d89682d5',
    messagingSenderId: '878308519120',
    projectId: 'waged-medical',
    storageBucket: 'waged-medical.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHV1_L_A6RRXU8uR6eYs2HvHOHZeYaZao',
    appId: '1:878308519120:ios:ae5b9d82695ef0349682d5',
    messagingSenderId: '878308519120',
    projectId: 'waged-medical',
    storageBucket: 'waged-medical.appspot.com',
    iosBundleId: 'com.waged.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHV1_L_A6RRXU8uR6eYs2HvHOHZeYaZao',
    appId: '1:878308519120:ios:c910c9c54259c8f99682d5',
    messagingSenderId: '878308519120',
    projectId: 'waged-medical',
    storageBucket: 'waged-medical.appspot.com',
    iosBundleId: 'com.example.doctors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA_M10xOxk5-4N96EPkd2PDvPQNlnXS68',
    appId: '1:878308519120:web:32bb0d27002001739682d5',
    messagingSenderId: '878308519120',
    projectId: 'waged-medical',
    authDomain: 'waged-medical.firebaseapp.com',
    storageBucket: 'waged-medical.appspot.com',
    measurementId: 'G-WQKS7C0WXS',
  );
}
